ci: Modified commit-msg hook

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -17,8 +17,8 @@
 
 # This example catches duplicate Signed-off-by lines.
 
-if ! head -1 "$1" | grep -qE "^(BREAKING CHANGE|feat|fix|docs|test|style|refactor)(\(.+?\))?: .{1,}$"; then
-    echo "Aborting commit. Your commit message is invalid." >&2
+if ! head -1 "$1" | grep -qE "^(BREAKING CHANGE|feat|fix|ci|docs|test|style|refactor)(\(.+?\))?: .{1,}$"; then
+    echo "Aborting commit. Your commit message is invalid.Please Follow conventional commit (https://www.conventionalcommits.org/en/v1.0.0/)" >&2
     exit 1
 fi
 
